column_order = [
    'Client Name',
    'Campaign Description',
    'Franchise Name',
    'Campaign Type',
    'Product Name',
    'Product Detail',
    'Campaign Timing',
    'Year',
    'Campaign Region',
    'Campaign ID',
    'Campaign Name',
    'Partner Name',
    'Package Description',
    'Placement Description',
    'Ad Size (WxH)',
    'Ad Type',
    'Device',
    'Country',
    'Start Date',
    'End Date',
    'Buy Model',
    'Planned Impressions Multiplier',
    'Planned Impressions',
    'Planned Units (eg. CPV, CPE, CPI)',
    'CPM / Cost Per Unit',
    'Planned Net Cost',
    'Planned SOV %',
    'Reporting Source',
    'Agency Fee Rate',
    'Agency Fee Cost',
    'Ad Verification Rate',
    'Ad Verification Cost',
    'Verification Buffer Amount',
    'Verification Buffer Total',
    'Reporting Fee Rate',
    'Reporting Fee Cost',
    'Service Fee Rate',
    'Service Fee Cost',
    'Ad Serving Type',
    'Ad Serving Rate',
    'Ad Serving Cost',
    'Ad Serving Buffer Amount',
    'Ad Server Buffer Total',
    'Total Cost',
    'Targeting',
    'Placement Phase (If Needed)',
    'Placement Objective (If Needed)',
    'KPI (If Needed)',
    'Creative (If Needed)',
    'Copy (If Needed)',
    'Placement Name',
    'DCM Link',
    'Length',
    'Twitter Card Name',
    'Self Serve Campaign Name',
    'Clickthrough UTM',
    'Base URL',
    'UTM_Source',
    'Source',
    'UTM_Medium',
    'Medium',
    'UTM_Term',
    'Term',
    'UTM_Content',
    'Content',
    'UTM_Campaign',
    'Campaign',
]

